language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
env:
  - TYPO3_VERSION="6.2.*"
  - TYPO3_VERSION="7.1.*"
  - TYPO3_VERSION="dev-master"
before_script:
  - composer self-update
  - composer install
install:
  - >
    if [[ "7.1.*" != "$TYPO3_VERSION" ]]; then
      echo "Overriding typo3/cms with version $TYPO3_VERSION";
      composer require typo3/cms:${TYPO3_VERSION}
    fi
script:
  - ./vendor/bin/runtests
